# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FilterCapture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FilterCapture
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SnapKit'

  target 'FilterCaptureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FilterCaptureUITests' do
    # Pods for testing
  end

end
